//
//  ToolbarIcons.h
//  TableTool
//
//  Created by Andreas Aigner on 31.07.15.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <Cocoa/Cocoa.h>


@interface ToolbarIcons : NSObject

// Generated Images
+ (NSImage*)imageOfAddLeftColumnIcon;
+ (NSImage*)imageOfAddRightColumnIcon;
+ (NSImage*)imageOfDeleteColumnIcon;
+ (NSImage*)imageOfAddRowBelowIcon;
+ (NSImage*)imageOfAddRowAboveIcon;
+ (NSImage*)imageOfDeleteRowIcon;

@end
